### ISSUE TITLE
Catch for non-existent jobs

### ISSUE THREAD

**Issue by KOOKIIEStudios** [Bratah123/SwordieDB#1]
### The following error was received when attempting to get job name of invalid ID:
![image](https://user-images.githubusercontent.com/25145447/98761656-e382aa00-2410-11eb-867d-ef9ea252e211.png)

### Job ID is `0`. Details extracted from DB for reference:
id | characterid | characteridforlog | worldidforlog | name | gender | skin | face | hair | mixbasehaircolor | mixaddhaircolor | mixhairbaseprob | level | job | str | dex | inte | luk | hp | maxhp | mp | maxmp | ap | sp | exp | pop | money | wp | extendsp | posmap | portal | subjob | deffaceacc | fatigue | lastfatigueupdatetime | charismaexp | insightexp | willexp | craftexp | senseexp | charmexp | noncombatstatdaylimit | pvpexp | pvpgrade | pvppoint | pvpmodelevel | pvpmodetype | eventpoint | albaactivityid | albastarttime | albaduration | albaspecialreward | burning | charactercard | accountlastlogout | lastlogout | gachexp | honorexp | nextavailablefametime
---| ---| ---| ---| ---| ---| ---| ---| ---| ---| ---| ---| ---| ---| ---| ---| ---| ---| ---| ---| ---| ---| ---| ---| ---| ---| ---| ---| ---| ---| ---| ---| ---| ---| ---| ---| ---| ---| ---| ---| ---| ---| ---| ---| ---| ---| ---| ---| ---| ---| ---| ---| ---| ---| ---| ---| ---| ---| ---
4 | 4 | 4 | 1 | Kookiiee | 0 | 0 | 23300 | 36786 | 0 | 0 | 0 | 1 | 0 | 12 | 5 | 4 | 4 | 50 | 50 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 4 | 4000011 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 4 | 0 | 0 | 0 | 0 | 0 | 0 | 0 | 1601-01-01 11:13:45.000 | 0 | 0 | 0 | 4 | 4 | 1601-01-01 11:13:45.000 | 0 | 0 | 1601-01-01 11:13:45.000

## Suggested solutions
3 plausible solutions:
1. **Use of try-except**
    - To catch the error
2. **Use of if-else**
    - To handle job ID of `0` without raising error
3. **Add `0` to jobs.json**
    - Easiest circumvention
    - May cause further problems down the line

**Comment by Bratah123** [comment]
Fixed by removing the json parsing and reading all together and instead adding a dictionary in the init.py file where the method can read from instead!
