### ISSUE TITLE
Raise Minor version to 2

### ISSUE THREAD

**Issue by KOOKIIEStudios** [Bratah123/SwordieDB#4]
**Suggestion:**
Raise Minor version to 2: _v0.2.0_

**Rationale:**
All known features (with the exception of the incomplete/insecure password change method) of User handler has been [tested](https://github.com/KOOKIIEStudios/ProjectShieldieDB) for correctness.
![image](https://user-images.githubusercontent.com/25145447/98975427-0fa54480-2551-11eb-9613-eea2f4713a13.png)

**Comment by Bratah123** [comment]
updated to minor version 2!
