### ISSUE TITLE
Equip tab handling missing from swordie_db.character

### ISSUE THREAD

**Issue by KOOKIIEStudios** [Bratah123/SwordieDB#5]
The Equipped window (column: `equippedinventory`) is handled by not the Equip tab in Inventory (cloumn:  `equipinventory`).

Attributes currently handled (Extracted from [API Docs](https://kookiiestudios.github.io/ProjectShieldieDB/character.html#swordie_db.character.Character)):
![image](https://user-images.githubusercontent.com/25145447/98985489-97de1680-255e-11eb-8a1d-a7326d877cb5.png)

**Comment by Bratah123** [comment]
thanks! fixed as of f6e2e1156f6a3bbe34b0ca83ce94f14a45f380a4
