### ISSUE TITLE
Raise Minor version to 3

### ISSUE THREAD

**Issue by KOOKIIEStudios** [Bratah123/SwordieDB#6]
**Suggestion:**
Raise minor version to 3: *v0.3.0*

**Rationale:**
All core unit tests passed from Python 3.6.12 to Python 3.9.0  
  
*Python 3.6.12*
![ver3612](https://user-images.githubusercontent.com/25145447/99078301-28693500-25f9-11eb-982d-909cd9078e6f.png)

*Python 3.9.0*
![ver390](https://user-images.githubusercontent.com/25145447/99078409-4fc00200-25f9-11eb-8fc5-08939c33512a.png)

**Comment by Bratah123** [comment]
SwordieDB has been pushed to v1.0.0 as it has reached intended functionality!
